### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by cyberchief1984** [Igglybuff/awesome-piracy#11]
I have a question... Will this get taken down? I promise, I won't report this.

**Comment by Igglybuff** [comment]
Maybe.

**Comment by Nufflee** [comment]
Piracy of course isn't legal... @Igglybuff

**Comment by mbobcik** [comment]
but links are not piracy, right?

**Comment by Igglybuff** [comment]
Right :)

**Comment by Nufflee** [comment]
Promoting piracy websites is illegal afaik

**Comment by arnavs** [comment]
SCOTUS:

> We hold that one who distributes a device with the object of promoting its use to infringe copyright, as shown by clear expression or other affirmative steps taken to foster infringement, is liable for the resulting acts of infringement by third parties.

“Clear expression” and “affirmative steps” are a high bar, but the name, history, and content in this repo make it a slam dunk. I think you should delete it

**Comment by gkeegan** [comment]
"Distribute a device" is very vague. I would assume that would refer to streaming boxes, not links to websites. If linking to websites were illegal, Wikipedia would be in trouble, since the wiki page of thepiratebay has the link to the site.

**Comment by AlbertosaurusrexDK** [comment]
It certainly depends. I have copied the repo down to my PC, so if it gets taken down, i can send over the files to Igglybuff in case he dosen't have them. Furthermore, the list is also available on pastebin. 

Github shouldn't have a problem with the list. I've found really destructive stuff on Github.

**Comment by wadbr** [comment]
What piracy? Aren't these all Linux ISOs mirrors?
