### ISSUE TITLE
Make into an importable bookmarks file

### ISSUE THREAD

**Issue by acavataio** [Igglybuff/awesome-piracy#129]
Is there a way that the contents of this list could be converted into a FFox or Chrome bookmarks file, so each of the sections would be folders and each of the links would be separate links in that folder?  If so, please do so or let me know, otherwise I will try to figure it out by myself and then share with everyone.  Thank you so much for this AWESOME LIST!

**Comment by Igglybuff** [comment]
Possibly - I can make a note to look into it 🙂

**Comment by Igglybuff** [comment]
I wrote a small bash script to generate a `bookmarks.html` file which you can import into Chrome. It treats _every_ heading as a folder so the directory tree is fairly flat. Feel free to submit a PR if you want to improve the output of the script.

The output of the script is here: https://raw.githubusercontent.com/Igglybuff/awesome-piracy/master/bookmarks.html

The script itself is here: https://github.com/Igglybuff/awesome-piracy/blob/master/create-bookmarks.sh
