### ISSUE TITLE
Add spotify premium mod apk

### ISSUE THREAD

**Issue by the4anoni** [Igglybuff/awesome-piracy#132]
https://forum.mobilism.org/viewtopic.php?f=1332&t=2950704 add this guys

**Comment by metroid112** [comment]
Commenting here so I follow this

**Comment by Igglybuff** [comment]
Scrolling through the comments, this APK sounds a bit brittle - does it actually work?

**Comment by OzakIOne** [comment]
I've been using his APK for two years now and I never had anything weird  happening to my phone

**Comment by Igglybuff** [comment]
Added :)

**Comment by the4anoni** [comment]
@Igglybuff Here is newer version https://forum.mobilism.org/viewtopic.php?f=1332&t=3038223
You linked old one.
