### ISSUE TITLE
Add a new Games index.

### ISSUE THREAD

**Issue by JonAugust123** [Igglybuff/awesome-piracy#133]
Hello guys. 
I find a good website who share direct links from Scene Releases, of trustful sources.

It's call GamesTurret, maybe a paradox of Torrent.
There it is: https://gamesturret.ga/

**Comment by metroid112** [comment]
Commenting here so I can follow this

**Comment by Igglybuff** [comment]
Seems to have a pretty limited collection and the download links all hit an annoying money-for-clicks intermediary :confused: probably best to stick with some of the options already in the list.
