### ISSUE TITLE
'Streaming Apps' updates required

### ISSUE THREAD

**Issue by kevincosmos** [Igglybuff/awesome-piracy#136]
TerrariumTV is no longer in development.

This is a discord server that acts as a hub for numerous streaming apps:
APK'S 2 Day 
https://discord.gg/2qWqzN8

Here are names and links of other streaming apps that you may want to consider implementing 

AniméGlare
Website - https://animeglare.xyz/
Discord - http://tinyurl.com/y22u53nx
Download - http://animeglare.xyz/AGDownloads/AnimeGlare-1.0.0.8-x64.apk

AniméVibe
Website - http://animevibe.tv/
Discord - http://tinyurl.com/y36f64kb
Download - https://bit.ly/animevibe-apk

ApolloTV
Website - https://apollotv.xyz/
Discord - http://tinyurl.com/y4aatjaf
Download - https://houston.apollotv.xyz/ota/download

BeeTV
Website - http://beetvapk.me/
Download - https://tinyurl.com/ycevq3ya

Cinema
Website  - https://cinemaapk.com/
Download -  https://tinyurl.com/y7ylwzko

CKayTV
Website - http://ckaytv.com/
Download - http://ckaytv.com/Latest/app.apk

CoToMovies
Webiste - https://cotomovies.com/
Download - https://cotomovies.com/files/cotomovies_2.3.2.apk

Cyberflix (Terrarium Clone)
Website - https://cybercloud.media/
Facebook - https://www.facebook.com/groups/CyberFlixTV 
Download - https://tinyurl.com/y86ksgd6

DreamTV (Terrarium Clone)
Website - http://dream-tv.xyz/
Discord - http://tinyurl.com/y62bw7hm
Download - http://bit.ly/2HD1BL6

Morph TV (Morpheus Fork) 
Download -http://titaniumtv.xyz/Morph2.apk
Discord  - http://tinyurl.com/yxfn58jr

PhoenixTV (Morpheus Fork)
Download - https://tinyurl.com/y7z5zct8

TeaTV
Website - https://teatv.net/teatv-apk-download/
Discord -  http://tinyurl.com/y6hwf3db
Download - https://tinyurl.com/y83ezzem

TitaniumTV (Terrarium Clone)
Webiste - http://titaniumtv.xyz/
Download - http://apps.titaniumtv.xyz/app-release.apk

TVZion
Website - https://tvzionapp.live/
Reddit - https://www.reddit.com/r/TVZionApp/
Download - https://zionapp.live/d

UnlockMyTV (Cinema Clone AdFree)
Website - https://unlockmytv.com/
Download -  http://bit.ly/2Ruy0n0

**Comment by Igglybuff** [comment]
Thanks, I've added these now.
