### ISSUE TITLE
Dead link (TPB fake torrent remover)

### ISSUE THREAD

**Issue by PBJF** [Igglybuff/awesome-piracy#157]
https://www.reddit.com/r/Piracy/comments/78aicx/i_wrote_a_small_script_that_automatically_hides/ ded

(in userscripts)

**Comment by LemonadeCard** [comment]
Backup URL to the thread: http://rpiracy.ignorelist.com/Piracy/comments/7/8/a/i/c/x/i_wrote_a_small_script_that_automatically_hides.html

Greasyfork link: https://greasyfork.org/en/scripts/21980-hide-fake-torrents-on-the-pirate-bay
