### ISSUE TITLE
Add storegmail.com

### ISSUE THREAD

**Issue by Sj2594** [Igglybuff/awesome-piracy#167]
storegmail.com is good temp mail service with gmail address

**Comment by Igglybuff** [comment]
Interesting... how does this work exactly? I assume they just created a bunch of Google accounts and add random dots in the address prefix? Happy to add this if I can be sure it's not harvesting hacked Google accounts for reuse or anything

**Comment by omznc** [comment]
Looks like it's been taken down.

**Comment by llacb47** [comment]
Replaced with `https://smailpro.com/` I think.
