### ISSUE TITLE
[Suggestion] Blackmart

### ISSUE THREAD

**Issue by PERCE-NEIGE** [Igglybuff/awesome-piracy#173]
Hello, a suggestion: Blackmart.

**Comment by Igglybuff** [comment]
Interesting... what's the "official" website for this APK? Is it https://blackmart.club/ ?

**Comment by Shakil-Shahadat** [comment]
Dead site.

**Comment by sadstan123456** [comment]
@PERCE-NEIGE Please share the official site.
