### ISSUE TITLE
Please remove DockSTARTer

### ISSUE THREAD

**Issue by nemchik** [Igglybuff/awesome-piracy#175]
It looks like DockSTARTer was included https://github.com/flamerds/awesome-piracy/commit/868079fece106f343ff538a6296e7a5f32cc81ca but the project isn't aimed at piracy. There are apps in the collection (all apps are optional) that some people do choose to use for piracy, but also many apps that are not piracy related. Overall the project isn't built for the sole purpose of piracy even if it does turn out to be helpful.

**Comment by Igglybuff** [comment]
While the project itself might not be directly aimed at pirating, it is very related IMO. It's essentially providing a docker-compose file that lets you stand up a media server and/or seedbox in a few minutes. I'm going to [respectfully] leave it in 🙂
