### ISSUE TITLE
KISS sites listed are fake sites

### ISSUE THREAD

**Issue by rookiegrammer** [Igglybuff/awesome-piracy#177]
The KISS sites listed here are fake and not frequently updated. Please just note KISS sites such as kissanime, kissasian and kimcartoon to link to official kissanime reddit page for users to find official links.
https://www.reddit.com/r/KissAnime/

**Comment by Igglybuff** [comment]
Which sites specifically are fake?

**Comment by Shakil-Shahadat** [comment]
KissAnime is dead.
