### ISSUE TITLE
How to make PR?

### ISSUE THREAD

**Issue by cyberchief1984** [Igglybuff/awesome-piracy#18]
I really don't know how to use GitHub. How do I make a pull request?

**Comment by Igglybuff** [comment]
Hi @cyberchief1984, I would recommend learning the basics of Git version control. Here are some resources:

https://www.youtube.com/watch?v=OqmSzXDrJBk
https://help.github.com/articles/about-pull-requests/

You will first have to fork the repository, then make changes in your fork, and submit those changes in the form of a pull request to this repository. Good luck!
