### ISSUE TITLE
The ultimate guide to nintendo 3ds piracy has been taken down

### ISSUE THREAD

**Issue by itsmeharry** [Igglybuff/awesome-piracy#180]

**Comment by Igglybuff** [comment]
Can you find a mirror for it? Removeddit can't get the deleted post 😢

**Comment by itsmeharry** [comment]
Hello,
Here is a mirror to the post via the Internet Archive: https://web.archive.org/web/20181127044207/https://www.reddit.com/r/Piracy/comments/6h2vdd/the_ultimate_guide_to_nintendo_3ds_piracy/<https://web.archive.org/web/20181127044207/https:/www.reddit.com/r/Piracy/comments/6h2vdd/the_ultimate_guide_to_nintendo_3ds_piracy/>
Hope this helped!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by itsmeharry** [comment]
Don’t worry about my last email.
This mirror seems to work better: https://web.archive.org/web/20180323181225/https://www.reddit.com/r/Piracy/comments/6h2vdd/the_ultimate_guide_to_nintendo_3ds_piracy/<https://web.archive.org/web/20180323181225/https:/www.reddit.com/r/Piracy/comments/6h2vdd/the_ultimate_guide_to_nintendo_3ds_piracy/>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by LuuNyX** [comment]
https://3ds.hacks.guide/
Just use this guide
