### ISSUE TITLE
BTRACS seems to be dead

### ISSUE THREAD

**Issue by alyssoncs** [Igglybuff/awesome-piracy#212]
http://btracs.com seems to not be working

**Comment by PythonTryHard** [comment]
BTRACS is confirmed to be dead
![image](https://user-images.githubusercontent.com/31789326/71592103-7ef48e80-2b61-11ea-92e1-3519cb56864e.png)

**Comment by Shakil-Shahadat** [comment]
The link does not exist in the repo anymore.
