### ISSUE TITLE
3D models and resources

### ISSUE THREAD

**Issue by geekalert** [Igglybuff/awesome-piracy#228]
Hi, there! I was trying to add to the thread on reddit, but it seems both are now locked for comments. I would like to request a section for 3d models and resources. Since KAT lost all of those a couple of years ago, those of us who work with these resources regularly have found it incredibly difficult to find what we lost. It would be amazing if you could include some locations in your list. Thank you, in advance.

**Comment by edshelton** [comment]
CGPeers is a good choice AFAIK. Keep an eye on /r/OpenSignups to register :)
