### ISSUE TITLE
DANGER: newshosting.com CHARGE 78,50 euros plus 0.93 cents ROBBERY

### ISSUE THREAD

**Issue by bgman111111** [Igglybuff/awesome-piracy#231]
when someone enter in newshosting.com he will see 6.99 euros / month. But they LIE. THis mean they will charge you 12 months this mean x 12 months. 6,99 euros plus 0,93 cents x 12 = 84,81 euros . But they have some delet and charge only 78,50 euros plus ROBBERY 0.93 cents. I interner in my bank account and when i see it i inmediatelly write support newshosting.com PLEASE report newshoisting.com THEY can't ROBBERY MORE PEOPLES. I work for 2 hours 20 euros a day. So for me this 78,50 euros plus ROBBERY 0,93 cents ARE NOT POSSIBLE FOR ME. i attach photos from index newshosting.com that it cost 6.99 euros AND NOT 78,50 euros plus ROBBERY 0,93 cents. 
![20191229_222506](https://user-images.githubusercontent.com/52361713/71563212-d4f30480-2a83-11ea-81a8-7ae170a9a028.jpg)
![20191229_222525](https://user-images.githubusercontent.com/52361713/71563228-f9e77780-2a83-11ea-8440-730638e99155.png)

**Comment by bgman111111** [comment]
update 1: Hello,

Thank you for contacting support.  The special is offered as $6.99/month that is billed annually at $83.88/year. That said,  I have forwarded this request to our billing specialist to be reviewed. You can expect an update on this matter within a few business days. If you need any assistance in the meantime, please reach out to us in a new email ticket.

 

Thank you for your patience.
 

I received email from chris newshosting.com HOw i told him on the second e-mail

**Comment by bgman111111** [comment]
![20191229_234642](https://user-images.githubusercontent.com/52361713/71563829-7420f780-2a96-11ea-9c20-c95e72d65f19.png)

**Comment by edshelton** [comment]
Billing annually is completely normal... also not sure what your dispute with NewsHosting has to do with this list. They are a reputable Usenet provider. Sounds like you didn't read the fine print.

**Comment by Igglybuff** [comment]
Billing annually is completely normal... also not sure what your dispute with NewsHosting has to do with this list. They are a reputable Usenet provider. Sounds like you didn't read the fine print.

**Comment by bgman111111** [comment]
Igglybuff Sounds like you work for newshosting.com Look in the third message or click on this link: https://user-images.githubusercontent.com/52361713/71563829-7420f780-2a96-11ea-9c20-c95e72d65f19.png it show humankind that charge 6.99 euros every month. When they bill from credit card it didn't comment they are gonna try ROBBERY 78,50 euros. Put your brain in work. Im protecting other peoples NOT FAIL in the same ROBBERY. stop corporations ROBBERY peoples. when person buy with credit card IT CLEA

**Comment by mikhoul** [comment]
![image](https://user-images.githubusercontent.com/5678673/71605890-894f6200-2b3a-11ea-89c5-b640682720b4.png)

**Comment by bgman111111** [comment]
mikhoul for strange reason you cant be quoted. from what day who post your photo. as it 86.xx euros didnt appear when i try buy 6 euros / mo. the word 6 euros / mo mean by my lawyer 6 euros / mo. 6 eurod every months. if this is anual then 6 euros / anyal. Now how i say from start of rhis mesage. when i try pay 6.99 euros / mo. it didnt show what you show in the photo. total 8x.xx euros. as how i say i can't pay 8x.xx euros. UPDATE 1. i received this email INHUMAN LIE from newshosting.com:

lo,

We have verified the provided information and as requested, your account has been canceled; you will not be charged again. Your refund has been processed and should complete within the next 7-10 business days.

Regards,
Newshosting Support


But on 31/13/2019 newshosting.com HAS SAY ON BANK TO ROBBERY THIS 8X.XX dolars or 76x.xx euros. As today i enter in my bank and it was charged. i attach here newphoto. My lawyer tell me take photo proof and how my lawyer say. when we speak with newshostib.com they will put new function to show total price. So here is new prrof that newhosting.com ROBBERY MONEY. as they charge 29 12 2019. a good company will wsit until 9 day bank accept or cabcel pay. so what newshosting.com has do when i speak my lawyer he coment when we write to hostingdomain.com they will charge credit card and this has happend newshosting.com HAS ROBBERY on 31 12 2019 here is photo proof. newshosting.com has to cancel that has been charge and newshosting.com has accepted charge. So tofay im gonna xall my lawyer friend and ADVERT ny bank to INMEDIATELY... i will out true about THIS SHIT company. include there is 2.x euros commision... and 0.93 cent... so this is not 6 euros / mo... this is more than 6.99 euros... INHUMAN. newshosting.com comment refund has been canceled but on 31 12 2019 newdhosting.com ROBBERY 8x.xx dolars plus commisions... only PENDIND pay are 0.93 cents. this is more suspicious... I HAVE AND MY FRIEND LAWYER HAS PROOF of they email and photo. that is how usa work. ROBBERY INOCENT PEOPLES... and writing warez is against law. i dont xare about if someone gonna denounce your github account. putting link of warez sites and etc. is against law. 
![20200102_042518](https://user-images.githubusercontent.com/52361713/71650918-d8072280-2d19-11ea-8c97-2edf14531950.png)
![20200102_042535](https://user-images.githubusercontent.com/52361713/71650926-e6553e80-2d19-11ea-9c67-551d5a280bce.png)
