### ISSUE TITLE
Remove Private Internet Access Due to Kape Technologies Merger

### ISSUE THREAD

**Issue by xbjfk** [Igglybuff/awesome-piracy#233]
From the CyberGhost VPN Private Policy (Part of Kape Technologies):

> Lastly, we may share Non-personal Data associated with the use of our Website with 3rd part suppliers for the purposes of optimization of our Website and Services as well customer analytics (e.g.VWO, Facebook, Yahoo, Twitter, Bing, Google, Mixpanel, Instabug, BugSplat, OpenX etc). These third parties will use Non-personal Data and/or Personal Data relating to your use of our Website to evaluate your use of the Website, compile reports on Site activity and provide other Site activity and internet related services, all in accordance with their applicable privacy policy.
> 
> We may further collect and possibly share your Personal Data to enforce the Terms of Service. This may be done to prevent a crime or violation of our Terms of Service or to help solve a transgression that has been committed.
> 
> We also reserve the right to disclose your Personal Data as required by law and when we believe that disclosure is necessary to protect our rights and/or comply with a judicial proceeding, court order, or legal process served on our Web site.

**Comment by sakshatshinde** [comment]
+1
