### ISSUE TITLE
Notifications system for this repo

### ISSUE THREAD

**Issue by maximousblk** [Igglybuff/awesome-piracy#250]
I was wondering if there is a way to get notifications for only the final commits to this repo.
I know I can"watch" this repo but it has the option for releases and all conversations which is rude on my inbox.

It would be nice it you would start "releasing" the final list in possibly json which would also mean it could be a somewhat of an API.

*<sup>(I am trying to make a piracy blog and love to be able to get automated notifications if possible.)</sup>*

**Comment by Igglybuff** [comment]
This ties in with #269 - if this list turned into a website it could easily have a queryable API with these features.

**Comment by maximousblk** [comment]
can do!

this can easily be turned into a website with minor changes to the `readme.md`.
If it is on the to do list and you are accepting pull requests, i'll start working on it.

**Comment by maximousblk** [comment]
Here, check it out: https://piracy.now.sh/

Feedback are welcome.

**Comment by maximousblk** [comment]
@Igglybuff I'm thinking a telegram channel would be enough for updates. If you would like it to be automated, i think github actions could help

**Comment by maximousblk** [comment]
Now that I think about it, it's not worth it. Cuz if someone ( read: I ) would want to find something, they would refer to this list themselves. They don't need updates for the list, they need updates for the things that are on this list.

Sorry to bother.
