### ISSUE TITLE
dot.tk not working any more

### ISSUE THREAD

**Issue by maximousblk** [Igglybuff/awesome-piracy#259]
all the free domains are shown as unavailable.

doesn't do what it claims.

**Comment by g4rret** [comment]
they're unavailable because someone's got them already

![proof](https://files.catbox.moe/92ztxd.png)
![more proof](https://files.catbox.moe/lksom4.png)

**Comment by maximousblk** [comment]
@g4rret Maybe look at [this](https://send.firefox.com/download/2878967a8be1c879/#AfyoL4obFNzoVcwXT3VL4g) (make sure you see this within 7 days)

**Comment by omznc** [comment]
Can you resend that file? Maybe attach it to a more permanent host? You can definitely still get free domains but there's a catch. If someone already has the domain, of course can't register it. Also, if someone had a free domain which expired, Freenom will require the next person who takes it to pay a premium.

**Comment by Igglybuff** [comment]
Can confirm it doesn't work for _any_ domain name.
