### ISSUE TITLE
Transform Awesome Piracy into a web site

### ISSUE THREAD

**Issue by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [Igglybuff/awesome-piracy#269]
Hello @Igglybuff , I had an idea about creating a web site similar to Privacy Tools where people could get curated lists of resources to pirate securely and privately, I made a post on /r/privacy about it:

>I have an idea about a website similar to PrivacyTools where I/we recommend the best software, providers or services to be able to pirate safely and privately.
>
>I have already a list of possible sections and things to list. I am learning to code and I can also contribute with creating some logo or images if needed. Someone with a bit of experience in programming would be great since I still don't know back end development and I may fuck things up if I try to set a server securely. Also, other requirements would be to believe in piracy as an act of freedom and activism, not just as a way to get things for free, to not be a supporter of any kind of discriminatory acts, such as sexism, racism, homophobia, etc, and to not have any trouble with licensing the website under creative commons.
>
>If someone is interested please comment here and we can talk a bit more to see if we can work together. Thanks!

Here's the URL: https://old.reddit.com/r/Piracy/comments/foqk23/does_anyone_want_to_help_me_with_a_project_to/

Someone recommended me your repository and I thought it was great and that a lot of my ideas were already there, but still I think something more user friendly with some nice UI would be better. My idea was to grab the PT web site code and modified to fit the new project, it is released under the creative commons C0 license so there shouldn't be any problem with that, it would make things easier and it would also work as a tribute to them. I think I can afford a few months of hosting until it gets some donations.

Let me know what you think and if you are interested in doing this, I tried to look for a better way to contact you but I couldn't find any e-mail so I created an issue, I can delete it after I have seen a reply from you.

Thanks!

**Comment by AlbertosaurusrexDK** [comment]
Hello, I'd be interested to help out. It's quite some time since I've made a website, but i'll be willing to help. 

Email me at gitthrowaway@protonmail.ch

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> Hello, I'd be interested to help out. It's quite some time since I've made a website, but i'll be willing to help.
> 
> Email me at [gitthrowaway@protonmail.ch](mailto:gitthrowaway@protonmail.ch)

Great, I'll try to message you in an hour or so and we can talk better about the details.

**Comment by Rextheace** [comment]
> > Hello, I'd be interested to help out. It's quite some time since I've made a website, but i'll be willing to help.
> > Email me at [gitthrowaway@protonmail.ch](mailto:gitthrowaway@protonmail.ch)
> 
> Great, I'll try to message you in an hour or so and we can talk better about the details.

I got the mail thrown away - use this 


rextheace@protonmail.ch

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> > > Hello, I'd be interested to help out. It's quite some time since I've made a website, but i'll be willing to help.
> > > Email me at [gitthrowaway@protonmail.ch](mailto:gitthrowaway@protonmail.ch)
> > 
> > 
> > Great, I'll try to message you in an hour or so and we can talk better about the details.
> 
> I got the mail thrown away - use this
> 
> [rextheace@protonmail.ch](mailto:rextheace@protonmail.ch)

I guess you are the same person?

**Comment by Rextheace** [comment]
> > > > Hello, I'd be interested to help out. It's quite some time since I've made a website, but i'll be willing to help.
> > > > Email me at [gitthrowaway@protonmail.ch](mailto:gitthrowaway@protonmail.ch)
> > > 
> > > 
> > > Great, I'll try to message you in an hour or so and we can talk better about the details.
> > 
> > 
> > I got the mail thrown away - use this
> > [rextheace@protonmail.ch](mailto:rextheace@protonmail.ch)
> 
> I guess you are the same person?

Yes, I am apparently incapable of logging a password correctly on Dashlane, and i didn't feel like painting this over my main github account lol

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> > > > > Hello, I'd be interested to help out. It's quite some time since I've made a website, but i'll be willing to help.
> > > > > Email me at [gitthrowaway@protonmail.ch](mailto:gitthrowaway@protonmail.ch)
> > > > 
> > > > 
> > > > Great, I'll try to message you in an hour or so and we can talk better about the details.
> > > 
> > > 
> > > I got the mail thrown away - use this
> > > [rextheace@protonmail.ch](mailto:rextheace@protonmail.ch)
> > 
> > 
> > I guess you are the same person?
> 
> Yes, I am apparently incapable of logging a password correctly on Dashlane, and i didn't feel like painting this over my main github account lol

No problem, I have already sent you an e-mail.

**Comment by Rextheace** [comment]
Read and replied.

**Comment by Igglybuff** [comment]
I think this is generally a nice idea and the PrivacyTools site is certainly very attractive which could make for a good basis. I'd really like some way to index and tag every link in this repo to make it searchable in a useful and intelligent way, perhaps via ElasticSearch and a simple Flask app to start with.

It'd also be nice to have some uptime monitoring for each site via UptimeRobot or similar to automate the process of checking if a resource is still online/experiencing problems. If there's an open-source option here that'd be great - maybe blackbox endpoint monitoring via Prometheus would work.

**Comment by maximousblk** [comment]
Maybe check this out: https://piracy.now.sh/

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> I think this is generally a nice idea and the PrivacyTools site is certainly very attractive which could make for a good basis. 

Yeah, it is very attractive and it could save us the time of building something from scratch, and it would also look like some sort of tribute to them. 

>I'd really like some way to index and tag every link in this repo to make it searchable in a useful and intelligent way, perhaps via ElasticSearch and a simple Flask app to start with.

I have gone through the list and tried to give it a bit of order, it's not finished, but it's something considering how it's currently structured (which in my opinion does not help to see through the whole content).

> It'd also be nice to have some uptime monitoring for each site via UptimeRobot or similar to automate the process of checking if a resource is still online/experiencing problems. If there's an open-source option here that'd be great - maybe blackbox endpoint monitoring via Prometheus would work.

Here are a few, I think Cabot may be the best one, but I guess we should try and see.
https://alternativeto.net/software/uptimerobot/?license=opensource

----

>Maybe check this out: https://piracy.now.sh/

I think it looks cool so far, but I think a bit more of order, classifications and visuals would help it. What do you think about using PT's website as a template?  I could start working on a logo or helping with development, too.

----

What do you all say if we organize in some group chat and see if we can do this? I say Session is best, but Matrix could work, too.

**Comment by maximousblk** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe privacy.now.sh was made without disturbing the current repo. Using PT's template would mean restructuring the whole repo.

Any suggestions on what to improve would really help.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Yes, I know, but I think it's something that should be done, it'll be better in the future since it can create an easier navigation, but if you totally don't want to give it a more "website" feeling that's okay.

My suggestions are the same as before, more structure, categories, and visuals, I think a clickable index at the beginning would help, too.

**Comment by maximousblk** [comment]
That's totally depends on @Igglybuff's decision now. We cannot just take apart the project if the plan is not even being considered by the owner.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Technically we can, their work it's under the Creative Commons' C0 license and it's open source, we can start doing something else basing on this, I'm not saying that we should not give credit to them or something like that, and I would highly prefer if they are interested in the idea and participate, just saying.

**Comment by maximousblk** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe this is a well known repo. It would be better if this project itself was updated instead of a whole new project that no one knows of.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> @5a384507-18ce-417c-bb55-d4dfcc8883fe this is a well known repo. It would be better if this project itself was updated instead of a whole new project that no one knows of.

Yeah, obviously, and I think it would be awesome if they want to do this.

**Comment by Igglybuff** [comment]
IMO the problem to solve here is a bit different from what Privacy Tools is trying to achieve. This list has almost 1300 URLs, each one usually belonging to several categories. Indexing and tagging each link in a sensible way with useful metadata attached is step 1 - making it pretty comes much later.

Keeping this list up to date is also difficult, time-consuming, and very manual. I'm one person with a family and a day job so I don't have time to stay on top of issues and pull requests, so having some way to automate at least part of the process of finding and sorting resources would be great. Curating the list could also be made a lot easier.

I have some ideas for software that will help solve these problems which I'll start writing and pushing to GitHub when I find the time and motivation to do so. But essentially I want to watch and scrape resources like Reddit, Discord, Telegram, and IRC in piracy-related channels/subreddits/servers/groups for URLs and index them in a database.

**Comment by maximousblk** [comment]
Here is an update on my project of creating this repo into a website: https://piracy.now.sh/
@5a384507-18ce-417c-bb55-d4dfcc8883fe I now need help with creating a system on how to categorize the links.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> > I think this is generally a nice idea and the PrivacyTools site is certainly very attractive which could make for a good basis. I'd really like some way to index and tag every link in this repo to make it searchable in a useful and intelligent way, perhaps via ElasticSearch and a simple Flask app to start with. - @Igglybuff
> 
> > I think a clickable index at the beginning would help, too. - @5a384507-18ce-417c-bb55-d4dfcc8883fe
> 
> Here is an update on my project of creating this repo into a website: https://piracy.now.sh/
> the new site has a search and all the categories in a side bar which makes it more clean.
> I now need help with creating a system on how to categorize the links.
> 
> And @Igglybuff, Maybe you use my site as the official (or community) website for your repo and forget about maintaining anything else. That would be an easy solution to this issue. What do you guys think?

I think it's better, I like it so far. I have a system which I've worked on that should help with organization a bit, should I fill in an issue? I think I'm okay with using your website, but if Igglybuff agrees maybe the code should be merged with this repo or something? I don't know.

**Comment by maximousblk** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe  yes you can fill in an issue if want to help.

I would like to go with creating my own version. but if @Igglybuff wants, i can help create a similar website for this version. its super easy and has a nondestructive process. I'm using vuepress because if fits well with github too.

**Comment by Igglybuff** [comment]
I'd be happier merging your additions for a website into this repo but would like to take a look at the code and see if it's extensible and compatible enough to work with some of the ideas I have for the future of this resource. Feel free to make a pull request @maximousblk.

**Comment by maximousblk** [comment]
@Igglybuff the repo is https://github.com/maximousblk/piracy/ . take a look at it and tell me what you think.

**Comment by maximousblk** [comment]
> I want to watch and scrape resources like Reddit, Discord, Telegram, and IRC in piracy-related channels/subreddits/servers/groups for URLs and index them in a database.

@Igglybuff maybe take a look at [visualbasic6/chatter](https://github.com/visualbasic6/chatter)
