### ISSUE TITLE
Remove LastPass from the "Password Vaults" section

### ISSUE THREAD

**Issue by arctictangokilo** [Igglybuff/awesome-piracy#278]
They can't seem to avoid massive security vulnerabilities being discovered far later than they should, and part of that problem is because they're not open-source.

To be honest, BitWarden and KeePass probably cover every user need, but at the very least LastPass is too shoddy to be on the list.

**Comment by jmada** [comment]
Do you recommend migrating from lastpass to bitwarden? I love lastpass because of its multi platform functionality

**Comment by maximousblk** [comment]
@jmada bitwarden is olso cross platform and supports synchronisation between multiple devices. But I prefer using the Google's own password manager because I don't store anything else other than website passwords.

**Comment by rignaneseleo** [comment]
@jmada I used a LastPass user for 3 years and almost 2 years ago I switched to BitWarden because of its nature (open source & free). I've got many mac, ios, android devices and I can tell you that I've never got a problems. 

99% stressfree move (the 1% is for the day you have to move your pwd).

**Comment by jmada** [comment]
Thanks! I'm using Bitwarden know and I deleted my lastpass account xD

**Comment by omznc** [comment]
I can agree with using Bitwarden, it's beenn my go-to password manager for 2 years.
