### ISSUE TITLE
Add "XMedia Recode" to the Ripping, Transcoding, Converting, Encoding section

### ISSUE THREAD

**Issue by Trigus42** [Igglybuff/awesome-piracy#281]
[XMedia Recode](https://www.xmedia-recode.de/en/) is a free, light weight transcoder, editor, CD/DVD/BD ripper with support for subtitles, hardware acceleration and much more.

**Comment by forart** [comment]
Since is FFMPEG-based, there are similar (or even better) open source alternatives:
These are just few, more around:
https://alternativeto.net/software/xmedia-recode/?license=opensource

**Comment by soulspark666** [comment]
A good addition instead would be https://github.com/staxrip/staxrip

**Comment by forart** [comment]
@soulspark666 FastFlix too: https://github.com/cdgriffith/FastFlix
