### ISSUE TITLE
Add the following Ebooks websites

### ISSUE THREAD

**Issue by shyamjesal** [Igglybuff/awesome-piracy#282]
[PDFdrive](http://pdfdrive.com) PDF Drive is your search engine for PDF files. No annoying ads, no download limits
[Mobilism Forum](https://forum.mobilism.org/index.php) large collection of ebooks
[Memory of the world](http://library.memoryoftheworld.org) A new website containing a lot of books

**Comment by Shakil-Shahadat** [comment]
PDFdrive, Memory of the world is already added to https://github.com/Igglybuff/awesome-piracy#ebooks.
