### ISSUE TITLE
delete 6box

### ISSUE THREAD

**Issue by Chup123** [Igglybuff/awesome-piracy#332]

**Comment by maximousblk** [comment]
Why? What happened to 6box

**Comment by jmada** [comment]
I've just checked the website and it's working... Why would you do that?

**Comment by jmada** [comment]
Oh, nvm... I checked another website, I think the problem is here https://6box.me/

**Comment by maximousblk** [comment]
I did a quick google search and got [this](https://www.reddit.com/r/usenet/comments/ccp8g3/indexers_does_it_make_sense_to_join_multiple/etsts6r). Is this why you want it to be removed?

**Comment by Chup123** [comment]
this is the site right now: 

![image](https://user-images.githubusercontent.com/33879050/81100438-d4281e80-8f0c-11ea-9a6c-3ee4a145c7f1.png)
