### ISSUE TITLE
Doperoms, 3DSISO and 3dscia.com are dead.

### ISSUE THREAD

**Issue by UprisingPulse** [Igglybuff/awesome-piracy#335]
Under Rooms;

Doperoms, 3DSISO are both completely dead

3DSCIA.com got updated to http://www.3dscia.to/

**Comment by maximousblk** [comment]
@UprisingPulse Any source for this info?

**Comment by UprisingPulse** [comment]
What kind of source?

I tried them one by one, changed protocol, checked in https://www.uptrends.com/tools/uptime

**Comment by maximousblk** [comment]
Source like if they were taken down or it's just a maintenance period.

But if it's not working at all, that's enough for it to be removed.
