### ISSUE TITLE
Google Image "View Image" button was deleted

### ISSUE THREAD

**Issue by Invisible40** [Igglybuff/awesome-piracy#352]
The script Google Image "View Image" button no longer exists.

**Comment by llacb47** [comment]
Maybe doesn't work anymore.

`https://pastebin.com/kPTGycFk`

**Comment by maximousblk** [comment]
@llacb47 does your script work?

**Comment by llacb47** [comment]
Not mine, it's the deleted one.

**Comment by maximousblk** [comment]
New link:

https://greasyfork.org/en/scripts/392076-google-images-direct-link-fix

Maybe this works.
