### ISSUE TITLE
Add piracy.now.sh as an alternative to this repo

### ISSUE THREAD

**Issue by maximousblk** [Igglybuff/awesome-piracy#354]
Website: [piracy.now.sh](https://piracy.now.sh/) 
Repo: [maximousblk/piracy](https://github.com/maximousblk/piracy)

It started as an effort to turn this list into a website but became it's own thing. And the inactivity on this list made me create my own version.

So if my list could be accepted as an alternative list, that would be great.

**Comment by Shakil-Shahadat** [comment]
A decision needs to be made with this issue.

**Comment by Igglybuff** [comment]
I'm going to close this for now - it feels like the opportunity has passed and @maximousblk has gone his own way (with good reason).
