### ISSUE TITLE
BeyondHD ratio rules change

### ISSUE THREAD

**Issue by rottenjoker** [Igglybuff/awesome-piracy#355]
One of BHD's recruiters posted this in another tracker 2 years and 7 months ago:
>We used to be a ratio free tracker but due to abuse we set a global minimum ratio of 0.1, but we are still willing to make exceptions for long term seeders.

I assume BHD is no longer a ratioless tracker but I'm not a member there so I don't know if it has any futher changes.

BeyondHD (BHD) in [Private Trackers](https://github.com/Igglybuff/awesome-piracy#private-trackers)

BHD's link is dead too.

**Comment by Purfview** [comment]
Why this was removed?
Site is not dead: https://beyond-hd.me
