### ISSUE TITLE
Remove cock.li of the email provider list

### ISSUE THREAD

**Issue by gagzzz** [Igglybuff/awesome-piracy#358]
Hey,

I'll let you do the digging but cock.li is a fascist-run service.
Domain names such as rape.lol, hitler.rocks and nuke.africa are quite eloquent.

I hope you will update the repo to remove that!

Thanks for the great work

**Comment by llacb47** [comment]
The burden is on you to provide proof.

**Comment by Omega9** [comment]
>fascist-run service

Are you really that naive that you don't understant that they're not a fascists and doing this just to provoke people like you?
What does this have to do with fascism?

**Comment by matt-derrick** [comment]
it still makes them jerks, and not all that relevant to piracy imo.

**Comment by Omega9** [comment]
it's still a good service

**Comment by gagzzz** [comment]
yeah, google makes a very service too, thanks.
