### ISSUE TITLE
Adding cracks for multiple OS and how to check for viruses

### ISSUE THREAD

**Issue by WizardOfAus** [Igglybuff/awesome-piracy#36]
E.g. https://www.reddit.com/r/sjain_guides/comments/9g4t2u/adobe_cc_2018_full_indepth_guide_to_installing/

Only for windows? 

Should also add some details on how to check for viruses :)

**Comment by Igglybuff** [comment]
Hi, this link is already in the list under https://github.com/Igglybuff/awesome-piracy#software and there is an anti-virus section too :slightly_smiling_face:
