### ISSUE TITLE
Add MonkeyStream.net to the movies streaming websites list

### ISSUE THREAD

**Issue by freegital** [Igglybuff/awesome-piracy#371]
Hello, first of all, thank you so much for this awesome contribution to the Internet.

I would like to suggest a movies streaming website called MonkeyStream, it is growing constantly and has a huge movies database of diverse genres.

I tried to create a PR after forking the repo but i couldn't do it, the reason why i'm writing to you over here.

Here's the link to the website: https://www.monkeystream.net/

If you like it, then please add it and share it to others. Thanks in advance.

Keep up the great job.

**Comment by Shakil-Shahadat** [comment]
The site is dead.

**Comment by sadstan123456** [comment]
@freegital the site appears to be dead. Please share the updated link, or close the issue.
