### ISSUE TITLE
Add Mailfence to the list of email services 

### ISSUE THREAD

**Issue by resto1231** [Igglybuff/awesome-piracy#379]
Mailfence is an encrypted email collaboration suite. It has all the bells and whistles such as components for the mail, calendar, document editing & storage space, and address book. Each component comes with tons of features to ensure collaboration and security.

Here are the links to my sources.

Source#1:https://en.wikipedia.org/wiki/Mailfence
Source#2:https://blog.mailfence.com/about-mailfence/
Source#3:https://mailfence.com

*I am affiliated with Mailfence*

**Comment by Igglybuff** [comment]
Closing this for now as it's yet another item unrelated to piracy. Still need to write some docs about avoiding scope-creepy contributions...
