### ISSUE TITLE
Remove Nano Adblocker & Nano Defender from list.

### ISSUE THREAD

**Issue by nefty1029** [Igglybuff/awesome-piracy#383]
With the news of the recent transfer of ownership by the developer, as seen here:
https://github.com/jspenguin2017/Snippets/issues/2

Along with the recent discovery by gorhill about how the new updates of the programs are now collecting user data:
https://github.com/NanoAdblocker/NanoCore/issues/362#issuecomment-709428210

I would like to request the removal of these programs from this list.

**Comment by ScottRFrost** [comment]
Nano Adblocker can obviously be replaced with uBlock Origin.

On FIREFOX, Nano Defender is still safe (due to having a different maintainer), but on Chrome or Edge what is the suggested replacement for Nano Defender?

**Comment by jmada** [comment]
> Nano Adblocker can obviously be replaced with uBlock Origin.
> 
> On FIREFOX, Nano Defender is still safe (due to having a different maintainer), but on Chrome or Edge what is the suggested replacement for Nano Defender?

You can user uBlock Origin on Chrome, Brave, Vivaldi, etc..

**Comment by ScottRFrost** [comment]
Yes, but what about a replacement for Nano DEFENDER (which defeats many anti-adblocker issues on common sites)?

**Comment by CyanoTex** [comment]
> Yes, but what about a replacement for Nano DEFENDER (which defeats many anti-adblocker issues on common sites)?

Can I bring up filterlists.com for possible filter list suggestions regarding adblock defusion?

**Comment by llacb47** [comment]
> Yes, but what about a replacement for Nano DEFENDER (which defeats many anti-adblocker issues on common sites)?

uBlock Origin already takes care of anti-adblock.

**Comment by nefty1029** [comment]
> Nano Adblocker can obviously be replaced with uBlock Origin.
> 
> On FIREFOX, Nano Defender is still safe (due to having a different maintainer), but on Chrome or Edge what is the suggested replacement for Nano Defender?

I did not know that Nano Defender has a different maintainer in Firefox. 
In that case, just put a note to only use Nano Defender in Firefox and not in Chrome.

**Comment by cgorlla** [comment]
The (new) Nano Defender has officially been deemed malware by Google. 
![Extension automatically disabled.](https://user-images.githubusercontent.com/18127268/96515209-c8f65000-1219-11eb-9d49-64d89b975745.png)

**Comment by givemeatip** [comment]
I trusted Nano Adblocker & Nano Defender and now they are infected by malware according to Google. So what are the recommended procedures now, basically change all our used passwords or they didn't compromise such data? What exactly were they spying? Just the sites we browsed, texts we may have typed or something more dangerous such as login credentials as well? 
Planet Earth keeps being a difficult place to live, our trust gets broken regularly in so many things.

**Comment by jonyroda97** [comment]
@givemeatip i will leave you with this link to this comment and follow the rest of comments there https://github.com/jspenguin2017/Snippets/issues/2#issuecomment-712469408

**Comment by Igglybuff** [comment]
Removed them both. Thanks for flagging!

**Comment by Hrxn** [comment]
> Yes, but what about a replacement for Nano DEFENDER (which defeats many anti-adblocker issues on common sites)?

In 99.99% of all possible cases, you don't need anything other than uBlock Origin.
So this question is totally moot.
