### ISSUE TITLE
openload userscript can be deleted

### ISSUE THREAD

**Issue by NLZ** [Igglybuff/awesome-piracy#384]
The OpenLoad domain has been seized by seized by alliance4creativity, so I think the openload userscript can be deleted from the listing as well.

**Comment by jmada** [comment]
+1

**Comment by NLZ** [comment]
Taking a closer look, some other listed userscripts are problematic as well:

- **anti-anti-copy**: only works for one domain (studytonight.com, as included)
- **Google Drive Direct Links**: the link points to the feedback/discussions, which can be confusing
- **Google Image "View Image" button**: dead link, userscript removed
- **Remove fake TPB torrents**: dead link, reddit post deleted

Some also seems to be couple years old, probably needs to be investigated if they are still works, like the google ones.

**Comment by Shakil-Shahadat** [comment]
I took care of OpenLoad and the four points you mentioned. Will check other scripts later.
