### ISSUE TITLE
VPN privacy concerns. (PIA - Private Internet Access)

### ISSUE THREAD

**Issue by frankpanduh** [Igglybuff/awesome-piracy#587]
PIA (Private Internet Access) is owned by "Kape Technologies" (formerly Crossrider). 

Sources:
https://restoreprivacy.com/kape-technologies-owns-expressvpn-cyberghost-pia-zenmate-vpn-review-sites/

https://torrentfreak.com/private-internet-access-to-be-acquired-by-kape/

https://torrentfreak.com/private-internet-access-to-be-acquired-by-kape/amp/

**Comment by Shakil-Shahadat** [comment]
Dupe of #233
