### ISSUE TITLE
r/YuzuPiracy is now r/NewYuzuPiracy

### ISSUE THREAD

**Issue by dhasial** [Igglybuff/awesome-piracy#593]
r/YuzuPiracy was banned along with some of the former creators / moderators.
Previous members have now made https://www.reddit.com/r/NewYuzuPiracy/ in its stead. Hopefully it gets to live a little longer than its predecessor.

**Comment by SmokeShine** [comment]
r/NewYuzuPiracy is also banned.

https://www.reddit.com/r/NewYuzuPiracy/

```
r/NewYuzuPiracy has been banned from Reddit
This subreddit was banned due to a violation of Reddit's [content policy](https://www.redditinc.com/policies/content-policy) against creating or repurposing a sub to reconstitute or serve the same objective as a previously banned or quarantined subreddit.
```

**Comment by Anvil5465** [comment]
Looks like there's a new community on Lemmy

https://lemmy.dbzer0.com/c/newyuzupiracy
