### ISSUE TITLE
Add Tidal-Media-Downloader

### ISSUE THREAD

**Issue by soulspark666** [Igglybuff/awesome-piracy#595]
I was suggested that it works, so I hope its added.
[CLI](https://github.com/yaronzz/Tidal-Media-Downloader) supports Windows \ Linux \ Macos \ Android
[GUI](https://github.com/yaronzz/Tidal-Media-Downloader-PRO) supports Windows

**Comment by forart** [comment]
...and what about [streamrip](https://github.com/nathom/streamrip) ?

Note: [interesting discussion](https://github.com/shirooo39/MiXLab/issues/23) about "integrating" a Tidal/Deezer/etc. music downloader in [MixLab](https://github.com/shirooo39/MiXLab/)

**Comment by Munmun6392** [comment]
Hello @aldoborrero Is this issue still open or fixed, if open I want to work on this.
Please assign this to me.
