### ISSUE TITLE
Merge /u/nbatman's streaming sites list

### ISSUE THREAD

**Issue by Igglybuff** [Igglybuff/awesome-piracy#60]
/u/nbatman has given me permission to merge [his list](https://www.reddit.com/r/FREEMEDIAFUCKYEAH/comments/9q11kg/how_to_stream_movies_tv_anime_sports_online/) into awesome-piracy.

**Comment by AlbertosaurusrexDK** [comment]
I'll merge it when i get home, and make a pull request.

**Comment by loonietoonie** [comment]
I dont have anything better. I'll add bits and pieces

**Comment by NiceHacksDude** [comment]
Possibly Fixed: https://github.com/Igglybuff/awesome-piracy/pull/110

**Comment by Igglybuff** [comment]
This has been completed :)
