### ISSUE TITLE
Is this repo still being updated?

### ISSUE THREAD

**Issue by soulspark666** [Igglybuff/awesome-piracy#607]
**Since last PR closed**
![PR](https://user-images.githubusercontent.com/37495396/148651248-34381a90-8a1b-4b33-9bb1-24331316fc8e.png)
**and last commit merged**
![Commit](https://user-images.githubusercontent.com/37495396/148651236-05f9fd3a-89d4-4b92-9e4b-38599ecb7b31.png)

So I had this question, if this is still being maintained by the author, or do some other fork is now the main, or someone else has created another similar to this.

**_PS: This is just a query and if I am missing any message from the author stating his absence then I would be glad to be redirected to it._**

**Comment by CZTeo** [comment]
The last merged request wqs 9months ago,i guess its not being maintained for now,if there are other active forks from this let me know

**Comment by Shakil-Shahadat** [comment]
I used to contribute to this repo and did 98 commits, many of them are merged. See https://github.com/Igglybuff/awesome-piracy/pulls/Shakil-Shahadat. The last merged commit in this repo was mine too.

I forked this repo and updated it a bit https://github.com/Shakil-Shahadat/awesome-piracy/commits/master. I wish to start updating soon especially merging the unmerged commits in these repo and other issues reported here.

If anyone wishes to contribute, you are welcome here https://github.com/Shakil-Shahadat/awesome-piracy.

**Comment by soulspark666** [comment]
@Shakil-Shahadat will you be merging the pending PRs

**Comment by Shakil-Shahadat** [comment]
Of course, I'll. I'll go through every open PR and even some closed ones. Some of my PRs were closed for unusual reasons.

I have already gone through all issues and done whatever I can.

I have some really interesting PRs like https://github.com/Igglybuff/awesome-piracy/pull/528 that I want to implement in my fork.

I will go through each link of the repo and also implement an automated link checker to find broken links.

Anybody who wishes to check my contribution in this repo can check this https://github.com/Igglybuff/awesome-piracy/pulls?q=is%3Apr+author%3AShakil-Shahadat+is%3Aclosed.

**Comment by soulspark666** [comment]
Seems like its back now, will be closing this then.
