### ISSUE TITLE
Please remove recorders, add legit downloaders

### ISSUE THREAD

**Issue by freestuffislove** [Igglybuff/awesome-piracy#634]
Spytify(stated) and Downtify are only recorders, they do not help in ripping. It would be appreciated if you could create a new section strictly for rippers only, or update the existing ones. Also, I would like to know why AniMixPlay is not mentioned in the list of anime streaming sites.

**Comment by Tosoju** [comment]
This list is no longer updating, so he likely didn't know about it at the time

I'm updating a list on my own list
