### ISSUE TITLE
Panel shows

### ISSUE THREAD

**Issue by recoilcontrolnone** [Igglybuff/awesome-piracy#645]
The website for panel shows is just a dead link. Is there a chance that it could be updated?

**Comment by Shakil-Shahadat** [comment]
This repo hasn't been updated for more than a year. I just removed it from my [fork](https://github.com/Shakil-Shahadat/awesome-piracy).

**Comment by recoilcontrolnone** [comment]
Is your fork frequently updated?

**Comment by Shakil-Shahadat** [comment]
I plan on updating it regularly. Especially if anyone opens a new issue / sends pr, they will be taken care of quickly. I'll also add/take care of all issues and prs of this repo. I have a lot of pr in this repo too.

**Comment by recoilcontrolnone** [comment]
I started looking at your fork and it's quite nice to have. You are doing gods work🙏. I will try to make some commits to this when it comes to music.
