### ISSUE TITLE
Magazines Section

### ISSUE THREAD

**Issue by xTheWhiteTigerx** [Igglybuff/awesome-piracy#650]
Both magazine sources appear to be down. A stopgap can be found here:
freemagazines.top

Other magazine sources can be found here:
https://www.similarweb.com/website/magazinelib.com/competitors/

**Comment by Shakil-Shahadat** [comment]
https://magazinelib.com/ is working. Removed http://pdf-giant.com/ from my fork https://github.com/Shakil-Shahadat/awesome-piracy#magazines-ok. I also added freemagazines.top and a couple of links from similarweb and from my collection.
