### ISSUE TITLE
Proxy Sites Dead Links

### ISSUE THREAD

**Issue by GiveMeEstrogen** [Igglybuff/awesome-piracy#673]
The links for Unblocked and ByPassed are both dead; Unblocked goes nowhere and Bypassed redirects to a scummy dating site

**Comment by soulspark666** [comment]
@GiveMeEstrogen did you check it on this fork
https://github.com/Shakil-Shahadat/awesome-piracy
Since this repo is mostly dead and @Shakil-Shahadat maintains a fork which accepts all PR from this.

**Comment by GiveMeEstrogen** [comment]
i did not, many thanks!
