### ISSUE TITLE
Suggestion - pSearch

### ISSUE THREAD

**Issue by SerjSX** [Igglybuff/awesome-piracy#675]
I've coded this program with Python for multi-searching piracy sites taken from the Piracy megathread, this megathread, and FREEMEDIAHECKYEAH's megathread (I add more sites on the program occasionally).

Before it was just via cmd line, but since I implemented GUI with Tkinter wanted to share it here as well, now it's more user friendly than before.

Here is the link to the site - https://serjsx.github.io/wpSearch/ 

Lmk how it goes, and if it isn't allowed no problem. I've tested it on my pc only, so hopefully there won't be any issues running it on other computers.

**Comment by BNX070** [comment]
> I've coded this program with Python for multi-searching piracy sites taken from the Piracy megathread, this megathread, and FREEMEDIAHECKYEAH's megathread (I add more sites on the program occasionally).
> 
> Before it was just via cmd line, but since I implemented GUI with Tkinter wanted to share it here as well, now it's more user friendly than before.
> 
> Here is the link to the site - https://serjsx.github.io/wpSearch/
> 
> Lmk how it goes, and if it isn't allowed no problem. I've tested it on my pc only, so hopefully there won't be any issues running it on other computers.

This is pretty dope, Thanks!
