### ISSUE TITLE
Add extension

### ISSUE THREAD

**Issue by Imparium** [Igglybuff/awesome-piracy#81]
[Burlesco](https://burles.co/en/) extension is, in my opinion, the best paywall bypasser extension ever.
They have native extensions for Chrome, Firefox and Opera. As well as a userscript.
It works with the following sites:

- Folha de S.Paulo
- O Globo
- O Estado de S. Paulo
- GaúchaZH
- Correio Popular
- Gazeta do Povo
- Diário Catarinense
- Jornal de Santa Catarina
- Diário de Santa Maria
- Nexo
- JOTA
- O Estado do Maranhão
- Jornal NH
- UOL
- Veja
- Exame
- Superinteressante
- Quatro Rodas
- The Economist
- Foreign Policy
- Financial Times
- The New York Times
- The Wall Street Journal
- The Washington Post

**Comment by Igglybuff** [comment]
Added :)
