### ISSUE TITLE
Can I add a Movie Release Types table?

### ISSUE THREAD

**Issue by sdushantha** [Igglybuff/awesome-piracy#83]
I would like to add something like this:

| Types    |Label            |Description  |
|----------|-----------------|-------------|
|Cam       |CAMRip, CAM      | Made using a camcorder or a mobile phone in a cinema. |
|Telesync  |TS, TELESYNC, PDVD | Made from professional camera and tripod from the cinema projection booth.|
|Telecine|TC, TELECINE|Copy froma film print using machine that transfers movies from analogue reel to digital format.|
|Pay-Per-View Rip|PPV, PPVRip|Made from pay-per-view service.|
|Screener|SCR, SCREENER, DVDSCR, DVDDCREENER, BDSCR| Early DVD release sent to movie reviewers or studio executives, which is then distributed.|
|Digital Distribution Copy|DDC|A digital version of a screener.|
|R5|R5, R5.LINE, R5.AC3.5.1.HQ|Retail DVD copy from region 5 (Russia, India, most of Africa)
|DVD-RIP|DVDRip| Retail version of a film, high-quality copy.|
|DVD-R|DVDR, DVD_Full, Full-Rip, ISO rip, lossless rip, untouched rip, DVD-5/DVD-9| Retail version of a fiml on a DVD, normally complete copy of DVD.|
HDTV/PDTV/DS/Rip| DSR, DSRip, SATRip, DTHRip, DVBRip, HDTV, PDTV, TVRip, HDTVRip, HDRip| Captured from a satellite or over-the-air feed. Often encoded to make file size smaller.|
|VODRip|VODRip, VODR|Rip form on-demand service such as cable TV.
|WEB-DL|WEBDL(P2P), WEB DL (P2P), WEB-DL (P2P), WEB (Scene)| Movie from online service such as iTunes Usually good quality|
|WEBRip|WEB-Rip, WEBRIP, WEB Rip|Taken from a DRM-free streaming service.|
WEBCap| WEB-Cap, WEBCAP, WEB Cap| Taken from a DRM-enabled service such as Netflix. Quality can vary.|
BD/BRRip|BDRip, BRRip, Blue-Ray/BluRay/BLURAY, BDR, BD5/BD9 (BD25/BD50)| Made from a Blu-way disc, normally high-quality|

**Comment by Igglybuff** [comment]
Hi, thanks for opening this issue. I added this in the `Miscellaneous` section today, actually.
