### ISSUE TITLE
Few changes for userscripts

### ISSUE THREAD

**Issue by LemonadeCard** [Igglybuff/awesome-piracy#87]
- [Anti-Adblock Killer](https://github.com/reek/anti-adblock-killer) has been abandoned for 2 years, many of the bypasses it uses are useless. Nano Defender is better choice, which is already on the list.
- [Popup Blocker Script](https://greasyfork.org/en/scripts/37654-popup-blocker-script) is [shady userscript](https://greasyfork.org/en/forum/discussion/36932/x), better alternative is [Popup Blocker by AdGuard](https://github.com/AdguardTeam/PopupBlocker) ([Greasy Fork link](https://greasyfork.org/en/scripts/33396-adguard-popup-blocker))

**Comment by Igglybuff** [comment]
I've made the adjustments mentioned in this issue. Thanks!
