### ISSUE TITLE
Add descriptions for all links that are missing them

### ISSUE THREAD

**Issue by Igglybuff** [Igglybuff/awesome-piracy#94]

**Comment by starrohan999** [comment]
hii

**Comment by IMPranshu** [comment]
Hey please assign this to me.

**Comment by kelvinparmar** [comment]
Hi I am beginner and I want to fix this please assign me and explain me

**Comment by SaiRev0** [comment]
If this issue is not assigned to anyone, can I work on this issue??

**Comment by AyushAgarwal15** [comment]
hey can I work in this issue please assign it to me

**Comment by soulspark666** [comment]
@AyushAgarwal15 this repo is dead mostly you can try to check things on @Shakil-Shahadat 's fork of this repo.

**Comment by Akhilvinay737** [comment]
hey i am beginner can i work on this??

**Comment by itsvanshchavda** [comment]
Hello can i work on this ?
