### ISSUE TITLE
Find more links for Audiobooks category

### ISSUE THREAD

**Issue by Igglybuff** [Igglybuff/awesome-piracy#96]

**Comment by piratebazaar** [comment]
the-eye.eu/public/AudioBooks/
audiobooks.cloud
tokybook.com

Please add these and please consider opening a telegram group for discussions and link sharing.

**Comment by Igglybuff** [comment]
Added :)

A Telegram group might be a good idea but I don't have the time to manage/moderate one. I am in the piracy Telegram group which you can find in the list.

**Comment by AudioBookClub** [comment]
> _No description provided._

Hi, please add AudiobookReviews.com too.
