### ISSUE TITLE
Find more links for Magazines category

### ISSUE THREAD

**Issue by Igglybuff** [Igglybuff/awesome-piracy#97]

**Comment by Manojkumarchow** [comment]
Hi @Igglybuff can I work on this? and can I get a brief description related to the issue?

**Comment by SaiRev0** [comment]
Can I work on this issue??

**Comment by Souvik-223** [comment]
Hello,I wish to work on this issue please guide me on how can i contribute.

**Comment by Siddheshuncodes** [comment]
Hi i want this to be my first contribution could you please guide me how can I can I contribute
